namespace: production
commonLabels:
  app: hasura
  env: production
resources:
  - ../base
replicas:
  - name: hasura
    count: 2
configMapGenerator:
  - name: hasura-config
    envs:
      - hasura-config.env
